name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build_type: release
          - os: macos-latest
            build_type: release
          - os: ubuntu-latest
            build_type: debug

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Install SDL via homebrew
      # Because ubuntu 22 doesn't have the latest SDL libs
      run: brew install sdl2
    - name: Configure CMake
      run: |
        mkdir ${{ matrix.build_type }}
        cmake -B ${{ matrix.build_type }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} occ
    - name: Build
      run: cmake --build ${{ matrix.build_type }} --config ${{ matrix.build_type }}
    - name: Test
      run: ctest -V
